### ISSUE TITLE
Weapons aren't receiving xp when using Cauldron

### ISSUE THREAD

**Issue by nerdnosyd** [bonii-xx/IguanaTweaksTConstruct#10]
I've just encountered a weird bug where only weapons were not receiving xp when launching a dedicated server using cauldron.  Tools like the hammer and mattock did receive xp.  Switched over to Forge and weapons are now receiving xp.

Tweaks version: 2.0.1.23
Cauldron version: 1.1199.01.149

**Comment by bonii-xx** [comment]
https://github.com/MinecraftPortCentral/Cauldron/issues/1560 Wait for new cauldron version.
Also I can't do anything about cauldron problems, since they're caused by cauldron to begin with. That's why it's unsupported by TConstruct.
