### ISSUE TITLE
Mattock not receiving xp when used as a shovel.

### ISSUE THREAD

**Issue by nerdnosyd** [bonii-xx/IguanaTweaksTConstruct#11]
A mattock isn't receiving xp when it's used as a shovel (digging dirt) but does when used as a hoe to till land and as an axe to chop down wood (though not slimy trees).  I'm unsure if this is intended or a bug but it seems like a bug since its made from a shovel head and it's description in the Materials book does say is effective on dirt.

**Comment by bonii-xx** [comment]
That actually is/was a TConstruct bug. Fixed in the next TConstruct version.
