### ISSUE TITLE
Crash when right cliking a cow.

### ISSUE THREAD

**Issue by sanedsf** [bonii-xx/IguanaTweaksTConstruct#13]
Right clicking a cow with an empty hand crashes the game. Which means that you cannot spam feed them. (Not right now at least.)

Encountered on version 2.0.0 and 2.0.1 BETA 2.

Below is a pastebin of the crash report.
http://pastebin.com/raw.php?i=bVffcr1G
## EDIT

After some research and my basic understanding of java the statement on line 23 in ClayBucketHandler.java tries to compare Nothing with a ClayBucketFired. And I believe that is the culprit right there.

If I am wrong about this, I apologize. I am just trying to help.

**Comment by bonii-xx** [comment]
No, the equipped item is null, therefore resulting in a nullpointer exception when I try to access it.
I simply forgot to check if the player has an item in the first place.
Fixed
