### ISSUE TITLE
A player needs to take out a cast and replace it to get it to work.

### ISSUE THREAD

**Issue by Ugaps** [bonii-xx/IguanaTweaksTConstruct#14]
Basically, I tried to make a chisel, and was surprised obsidian didn't work. I assume this is Iguana Tweaks's fault, due to the fact that it uses the stone parts a player used to make them.

**Comment by sanedsf** [comment]
I confirm this. And after some more tests I figured that this happens with every cast and only one occasion.

Steps for reproduction on version 2.0.1 Beta 2
1. Melt some Aluminum Brass or Gold to make a cast.
2. Melt any other material to make the part out of.
3. Pour the Brass or Gold over **ANY** stone part.
4. Do not remove the cast and try to pour the second material again.

There is no crash it just doesn't happen.

**Comment by bonii-xx** [comment]
Hm, that's quite possible. The cast is in the output-slot after creating it, but you need it in the input slot to pour into it.
Will take a look if that's fixable, since I have to revisit that part again anyway.

**Comment by sanedsf** [comment]
Is there a reason for having the casts go in the output slot anyway?

**Comment by bonii-xx** [comment]
Because it's the output of the casting process? ;o
But yeah, that's not doable in iguana tweaks, would have to be in tinkers itself.

**Comment by bonii-xx** [comment]
https://github.com/SlimeKnights/TinkersConstruct/pull/865
There you go :P

**Comment by sanedsf** [comment]
Nice. :+1:
