### ISSUE TITLE
block harvest level should be configurable

### ISSUE THREAD

**Issue by UndeadZeratul** [bonii-xx/IguanaTweaksTConstruct#18]
I'm looking to tweak the overall progression in my modpack, and I'm having trouble modifying the block hardness requirements.  The closest I've gotten to any real progression is using this mod.  However, Once I start tweaking the progression, it really breaks considering the blocks aren't changing.  I'd like tin to be below iron so that you have to make bronze to get to iron, then combine iron and bronze to get damascus steel to progress further; too bad tin is higher than iron.  I want nether metals to come after overworld and metallurgy fantasy metals; too bad iron can mine half of them.  Same with fantasy metals,  I can mine half of them with iron/copper/stone.  I'd like to stretch out the progression tiers, and I can't do that with the way the blocks are modified currently.

Looking through [this class](https://github.com/bonii-xx/IguanaTweaksTConstruct/blob/master/src/main/java/iguanaman/iguanatweakstconstruct/harvestlevels/HarvestLevelTweaks.java#L189-L279) it seems like the oredictionary entries are hardcoded in their own harvest levels.  I'm thinking this should be configurable, if not at least follow the tool harvest levels.

Are there current plans in place to allow block hardness modification?  if not, is this something worth considering?

**Comment by bonii-xx** [comment]
If you're referring to harvestlevels: https://github.com/bonii-xx/IguanaTweaksTConstruct/blob/master/src/main/java/iguanaman/iguanatweakstconstruct/override/BlockOverride.java
If your'e referring to actual block hardness, no plans so far.

**Comment by UndeadZeratul** [comment]
Oh sorry, I meant the level in which the block can be harvested.  I get those mixed up.

Where is the config file for that?  I think that's what I'm looking for, but I can't find where the file is created.

**Comment by bonii-xx** [comment]
It'll be in the next version.
