### ISSUE TITLE
Internal server error when joining server

### ISSUE THREAD

**Issue by silverches** [bonii-xx/IguanaTweaksTConstruct#20]
Hello,

I am getting an internal server error when i try to join a server.

Using: cauldron 1.1207.01.187,
Tcon: 1.6.0d39
Iguana Tweaks: 2.0.1b2.

The log is here: http://haste.pagefortress.com/dibuzifune.avrasm

Is there also an irc channel?

**Comment by bonii-xx** [comment]
Seems like you got a tinker tool without NBT. I disabled the automatic updating on login together with more safety checks, so it should be fine next version.
Tinker's Construct IRC channel also is for iguana tweaks.
