### ISSUE TITLE
Replacing tool TCT

### ISSUE THREAD

**Issue by smiletactician** [bonii-xx/IguanaTweaksTConstruct#24]
Hey,

this happened when i tried to place the tool ingot he craft grid. happened to be a tool station originally but i tried a few times with the same result in personal craft table.
http://pastebin.com/HfjQVw2D

smile

p.s.
while i'm here. is there some instruction to replacing parts? i can't find it covered very well, anywhere. either that or my tools really don't like being upgraded.

**Comment by bonii-xx** [comment]
Update TCon.
Part replacement is simple: tool must be fully repaired, apply new part like a modifier.

**Comment by smiletactician** [comment]
I have tried replacing and all the counterparts. Still, no joy.
Using modified Bevo's Tech Pack. I didn't know they were behind on TiC. I'll Look into it.

Thanks.
