### ISSUE TITLE
Enabling non-TiC does not work properly

### ISSUE THREAD

**Issue by Yulife** [bonii-xx/IguanaTweaksTConstruct#25]
Basically I have this config setting:

```
# Makes all non-TConstruct tools mine nothing [default: true]
B:disableRegularTools=false
```

Despite the fact that I disabled it, you still cannot mine AE2's Quartz which was required redstone mining level iirc. Instead it has the mining level of obsidian which makes AE2 rather lategame. However, some tools like the muddy pick (which is wooden mining level!) can mine the Quartz ore while an iron pick cannot.

**Comment by bonii-xx** [comment]
Sounds like you're confusing vanilla tool stuff with HarvestLevel tweaks.
Also according to the BoP source mud picks actually have diamond or higher mining level.

**Comment by Yulife** [comment]
Yeah, Iguana Tweaks is confusing me a bit. I never knew mud had diamond mining level.. that's rather op. Thanks for the clarification.

**Comment by bonii-xx** [comment]
No, it's not OP, it's a bug. ;)

**Comment by Yulife** [comment]
Please don't hit me but.. what numbers do I need to change to make it "Vanilla" like and not forcing you to use TiC? I want to offer flexibility in my modpack.

**Comment by bonii-xx** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2176855
You can find everything you need there.
