### ISSUE TITLE
Computercraft Turtle mining hardness

### ISSUE THREAD

**Issue by Maxwelljones** [bonii-xx/IguanaTweaksTConstruct#28]
The computercraft turtles don't mine harder blocks (ex. yellorite) but instead breaks them.
Would that be a way to tweak this? - As they are not regular tools but are "using" them.

**Comment by bonii-xx** [comment]
I believe I have looked into that once and the harvest level was hardcoded inside the turtles. Might have to ask dan to check that.

**Comment by Maxwelljones** [comment]
Ok thank you for your answer. I'll have that checked with Dan and get the info back to you.
