### ISSUE TITLE
Zombie head not working on iron pick

### ISSUE THREAD

**Issue by utoxin** [bonii-xx/IguanaTweaksTConstruct#8]
I'm not sure if this is an issue or not, but when I try to put a zombie head on an iron pick, it shows that it worked in the tooltip, but as soon as I try to pull it out of the table, it disappears from my cursor and drops back into the table without updating.

**Comment by utoxin** [comment]
It shows 'copper' mining level before I put the head on it, and 'iron' in the tooltip with the head in the upgrade slot.

**Comment by bonii-xx** [comment]
Sounds like you're using an old tool, since Iron picks cannot have copper mining level with iguana tweaks.

**Comment by utoxin** [comment]
I created it specifically to test this, since my old tools were all showing 'unknown' levels and such. (To avoid breaking them, I presume.) Iron tool rod, iron binding, iron pick head. I have the config that downgrades the mining level on, requiring the XP to boost it to the normal mining level.

Applying the head didn't work, so I tested mining a bunch of blocks, and when the mining experience went up, it went to the Iron mining level.

**Comment by utoxin** [comment]
(I'm running default config, just to be clear. Didn't change anything, although I looked through the whole file.)

**Comment by utoxin** [comment]
_tries to think what else you might need to know_ 1.7.10, running latest Tinker's Construct and your latest. Running default configs for both. Anything else you might need to know that I haven't thought of yet?

**Comment by bonii-xx** [comment]
Well, zombie heads are only applicable up to copper, for iron you need skeleton heads. Refer to the heads tooltips. The specifically created tool should have had mining level iron? And Tin once it's upgraded? I still suspect that you had an old pickaxe. I implemented some changes that warn you of "old" tools and a way to fix them in the latest dev version.

**Comment by utoxin** [comment]
I created a /brand new tool/ after installing the mod. Even the parts were new after install. And it had mining level copper when I created it, and upgraded to mining level iron after I'd used it enough to level up the mining XP. But i will check with the correct skull tonight. It said 'up to copper' which is why I tried it.

**Comment by bonii-xx** [comment]
Okay, a new iron pick should never show copper as mining level. Here's some things:
- Forge Version
- TConstruct Version
- Mantle Version
- Try if you can mine iron with an un-upgraded pickaxe that says copper mining level
- Tic-Tooltips installed? It probably displays a wrong mining level (which does not effect the iguana tweaks tooltip, however)

**Comment by utoxin** [comment]
Forge: 10.13.0.1198
Tinker's Construct: 1.6.0d38
Mantle: 0.3.0

I don't have Tic-Tooltips installed, and I'll test the mining when I get home.

**Comment by bonii-xx** [comment]
Ok, then try the other things above, and if it still doesn't work correctly tell me if it also happens with [this version](https://dvs1.progwml6.com/jenkins/job/IguanaTConTweaks-1.7.10/23/artifact/build/libs/IguanaTinkerTweaks-1.7.10-2.0.1.23.jar)

**Comment by utoxin** [comment]
Okay, just tested.

When I put the parts in the table, it shows that it will be Iron mining level. But when I pull it out, it only shows a Copper mining level. And the tool is indeed only Copper mining level. Works on Copper, but not on Iron. Grabbing the test version to load up next.

**Comment by utoxin** [comment]
My confusion level is growing.

Using the testing build you linked to, things work as I expected. Iron mining level, works on copper and iron.

So I switched back to the 'bad' version. The pick I'd created using the test version now shows a Copper mining level. So I made a new tool. And it shows an Iron mining level. Note that both of these tests were done locally, not on a server (which is where my initial tests were done.)

All other variables were the same between the two runs. Do you want me to do any additional testing?

**Comment by utoxin** [comment]
Huh. Exact same config and version (2.0.0) behaves differently in SMP. In Single Player, it creates the tool with the Iron mining level. In SMP, it creates it with a Copper mining level.

**Comment by utoxin** [comment]
I.... Um. Okay, I'm stumped. Unless loading the dev version does something to the world data that changes this behavior. I just tested on a second server using the test version, and saw the same pattern I saw in single-player. Creating a pick in test version worked. Reverting to 2.0.0 makes the pick I just made into a copper mining level pick, but a new pick is created properly, at Iron level.

**Comment by utoxin** [comment]
Copied over the config files as updated by the 2.0.1 version, and it fixed the 2.0.0 behavior. I suspect it was the Modules.cfg file. (Which didn't exist at all in the 2.0.0 directory.)

**Comment by bonii-xx** [comment]
Modules.cfg existed, but it was integrated in the TinkerModules.cfg ;)
So basically it seems to have been a problem with SMP? Hm. Well, as long as it works with the newest version it should be fine. Thanks for the testing, let me know if it happens again. :)
