### ISSUE TITLE
Unable to get some achievements if vanilla tools disabled

### ISSUE THREAD

**Issue by labpaw** [bonii-xx/IguanaTweaksTConstruct#9]
Yes, I know it is never working in original IguanaTweaks. So, it's some kind of suggestion. Well, when we start playing we can't make wooden and stone tools that means we can't get those achievements: "Time to Mine!", "Getting an Upgrade", "Time to Strike!". It makes me sad. So maybe it possible to make "Flint" tools triggering achievements? Because flint first material that we can get and make pickaxe and sword.  But I am don't know if it possible. Or maybe IguanaTweaks can override vanilla achievements? So, instead of wooden tools there are will be flint tools. And instead of stone pickaxe there are will be cooper (for example) pickaxe.

**Comment by bonii-xx** [comment]
Reasonable request, however it has no priority compared to all the missing stuff. Gonna put it at the bottom of my todo. ;)
